// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxV0AOF1OJPCuRLp0MeEFUELM4i5jyBHo',
    appId: '1:292939060485:web:45fc442271b265baab936c',
    messagingSenderId: '292939060485',
    projectId: 'test-bae8a',
    authDomain: 'test-bae8a.firebaseapp.com',
    storageBucket: 'test-bae8a.appspot.com',
    measurementId: 'G-TEH3S3CX9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwttKkJh005RzPtlO6XWGuGwIuatxIJE',
    appId: '1:292939060485:android:08607901d76169eaab936c',
    messagingSenderId: '292939060485',
    projectId: 'test-bae8a',
    storageBucket: 'test-bae8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDenxw4NB475tDbrhbqwrxWsARqZlmcZ4Q',
    appId: '1:292939060485:ios:0f021b29d4515a01ab936c',
    messagingSenderId: '292939060485',
    projectId: 'test-bae8a',
    storageBucket: 'test-bae8a.appspot.com',
    iosClientId: '292939060485-7ahq9fvfd0cjgttqalniceem3falbcjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytestbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDenxw4NB475tDbrhbqwrxWsARqZlmcZ4Q',
    appId: '1:292939060485:ios:619a646113453b0dab936c',
    messagingSenderId: '292939060485',
    projectId: 'test-bae8a',
    storageBucket: 'test-bae8a.appspot.com',
    iosClientId: '292939060485-89eb2t530hujrjcbkt8ea0jcd3975m5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytestbox.RunnerTests',
  );
}
